version: '3'

services:
  client-app:
    build:
      ./frontend
    labels:
      - "traefik.backend=client-app"
      - "traefik.frontend.rule=Host:localhost;PathPrefix:/"

  prefixed_api:
    build:
      ./api
    labels:
      - "traefik.backend=prefixed_api"
      - "traefik.frontend.rule=Host:api.localhost;AddPrefix:/api"
    env_file:
      - ./api/api_env
    depends_on:
      - postgres

  whoami:
    image: emilevauge/whoami
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:whoami.localhost;PathPrefix:/"
    restart:
      always

  proxy:
    image: traefik
    command: --web --docker --docker.domain=localhost --logLevel=INFO
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    restart:
      always
    labels:
      # Don't manage this in traefik
      - "traefik.enable=false"

  postgres:
    restart: always
    image: postgres:10
    env_file:
      - postgres.env
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    labels:
      # Don't manage this in traefik
      - "traefik.enable=false"

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - ./pgadmin/pgadmin.env
    volumes:
      - ./pgadmin/servers.json:/servers.json
    labels:
      - "traefik.backend=pgadmin"
      - "traefik.frontend.rule=Host:pgadmin.localhost;PathPrefix:/"
